apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  # 升级时使用，istioctl upgrade不支持--set
  # 指定install_package_path后必须同时指定profile，否则报错，默认会到install_package_path的路径下查找profiles/default.yaml
  # profile: default
  # install_package_path: ""
  hub: dockerhub.azk8s.cn/istio

  components:
    policy:
      enabled: true
    citadel:
      enabled: true
    galley:
      enabled: false
    egressGateways:
      - enabled: false

  addonComponents:
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true

  values:
    gateways:
      istio-ingressgateway:
        telemetry_addon_gateways:
          prometheus_gateway:
            enabled: true
          grafana_gateway:
            enabled: true
          kiali_gateway:
            enabled: true
          tracing_gateway:
            enabled: true
    prometheus:
      hub: dockerhub.azk8s.cn/prom
    kiali:
      hub: quay.azk8s.cn/kiali
      createDemoSecret: true
