{{ if or (eq .Values.revision "") (not .Values.clusterResources) }}
{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-pilot{{- if not (eq .Values.revision "") }}-{{ .Values.revision }}{{- end }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: pilot
    release: {{ .Release.Name }}
    istio: pilot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: pilot
      {{- if ne .Values.revision ""}}
      version: {{ .Values.revision }}
      {{- end }}
      release: {{ .Release.Name }}
      istio: pilot
---
{{- end }}
{{- end }}
