apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  hub: dockerhub.azk8s.cn/istio

  components:
    policy:
      enabled: true
    citadel:
      enabled: true
    galley:
      enabled: false
    egressGateways:
      - enabled: false

  addonComponents:
    prometheus:
      enabled: true
      k8s:
        replicaCount: 1
    kiali:
      enabled: true
      k8s:
        replicaCount: 1
    grafana:
      enabled: true
      k8s:
        replicaCount: 1
    tracing:
      enabled: true

  values:
    prometheus:
      hub: dockerhub.azk8s.cn/prom
      ingress:
        enabled: true
        hosts:
          - ingress.k8s.hbchen.com
    grafana:
      ingress:
        enabled: true
        hosts:
          - ingress.k8s.hbchen.com
      # Prometheus默认contextPath=/prometheus，datasource url需要增加path
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              orgId: 1
              url: http://prometheus:9090/prometheus
              access: proxy
              isDefault: true
              jsonData:
                timeInterval: 5s
              editable: true
    tracing:
      contextPath: /jaeger
      ingress:
        enabled: true
        hosts:
          - ingress.k8s.hbchen.com
    kiali:
      hub: quay.azk8s.cn/kiali
      createDemoSecret: true
      ingress:
        enabled: true
        hosts:
          - ingress.k8s.hbchen.com
