apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  profile: default
  hub: dockerhub.azk8s.cn/istio

  values:
    prometheus:
      hub: dockerhub.azk8s.cn/prom
      ingress:
        enabled: true
    grafana:
      enabled: true
      ingress:
        enabled: true
      # Prometheus默认contextPath=/prometheus，datasource url需要增加path
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              type: prometheus
              orgId: 1
              url: http://prometheus:9090/prometheus
              access: proxy
              isDefault: true
              jsonData:
                timeInterval: 5s
              editable: true
    tracing:
      enabled: true
      ingress:
        enabled: true
        hosts:
          - tracing.local
    kiali:
      enabled: true
      hub: quay.azk8s.cn/kiali
      createDemoSecret: true
      ingress:
        enabled: true

